# Generated by Django 5.1.5 on 2025-01-21 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_studentprofile_user'),
        ('job', '0002_remove_job_company_name_applicationform_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auths.studentprofile'),
        ),
    ]
